name: ACAntiCheat
main: com.yourcompany.uac.UltimateAntiCheatPlugin
version: 0.1.0
author: YourCompany
api-version: '1.20'
commands:
  acac:
    description: ACAntiCheat staff command
    usage: /acac stats <player>
    permission: acac.use
